# Generated by Django 3.0.5 on 2020-04-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0002_auto_20200408_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['book', 'book_num']},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter', 'chapter_num']},
        ),
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ['verse_num']},
        ),
    ]
